spring:
  application:
    name: order-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: ordersdb

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8081
portfolio:
  service:
    base-url: http://localhost:8082/api/portfolio

resilience4j:
  circuitbreaker:
    instances:
      hasEnoughBalance:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      hasEnoughBalance:
        maxAttempts: 2
        waitDuration: 2s
