spring:
  application:
    name: order-service

  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:ordersdb}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: ${SERVER_PORT:8081}
portfolio:
  service:
    base-url: ${PORTFOLIO_BASE_URL:http://localhost:8082/api/portfolio}

resilience4j:
  circuitbreaker:
    instances:
      hasEnoughBalance:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      hasEnoughBalance:
        maxAttempts: 2
        waitDuration: 2s
